### PR TITLE
Add student-t distribution

### PR DESCRIPTION
**Pull request by bdeket**
Following zip has the code that I used to test the new implementation (in bf): [studentttest.zip](https://github.com/user-attachments/files/17875770/studentttest.zip)
Thanks to @soegaard for setting up the base implementation and the tests

### CODE REVIEW

**Comment by soegaard** [comment]
Excellent work.

**Comment by jbclements** [comment]
@soegaard @bdeket I should probably deprecate my t-test package, is that right? Please forgive my laziness, I can't see the docs for the new code yet on racket-lang.org, and I'm almost certain to forget about this if I let it slide.

**Comment by samth** [comment]
@jbclements this is part of the `math` library so you won't see the docs update on docs.racket-lang.org until there's a new release.

**Comment by soegaard** [comment]
@jbclements

From my locally rendered documentation:

image
image

This addition to the math library contains the student-t distribution.
It does not contain tests that uses the student-t distribution.
In particular it doesn't contain the student-t-test.

So keep the `t-test` package - but internally rewrite the code to use the distribution
functions from the math library.

**Pull request merged**
