### PR TITLE
fllog+, fllog-quotient & fllog-hypot

### PR DESCRIPTION
**Pull request by bdeket**
in an elusive search to calculate `complex-gamma` i found following undocumented functions: `fllog+` & `fllog-quotient`.
This PR adds documentation for them and improves/adds boundaries for when to calculate in double-double.
Also for accurately calculating `(log z)`  a similar function is created: `fllog-hypot`

fllog+
* change boundaries for double-double calculation (upper boundary from 1.7 -> 2.7)
`(fflog+ -1.4293498385921057e-012 +2.5111776760269606)`

fllog-quotient
* correct handling if x is +nan.0
* double-double calculation if x/y is near 1
* avoid unnecessary multiplication with s
`(fflog-quotient 500000000001. +500000000000.)`
`(fflog-quotient +nan.0 +2.)`

fllog-hypot
* avoid over/underflow
* accuracy where (hypot x y) is near 1
`(fllog-hypot 1e-321 +1e-320)`
`(fllog-hypot 1.1084129893159664 +1.619387121491612e-005)`

### CODE REVIEW

**Comment by soegaard** [comment]
@bdeket @pavpanchekha Is this ready to merge?

**Comment by bdeket** [comment]
For me it is, unless you have comments.

**Review by pavpanchekha — APPROVED** [review]
A yes from me too. I didn't prove the error bounds but at least the approach makes sense and my intuition is error should be low. It'd be good to have this available in the `math` library. Let's merge.

**Comment by soegaard** [comment]
Thanks - sorry for the delay.

**Pull request merged**
